version: 2.1
orbs:
  win: circleci/windows@1.0.0
jobs:
  build:
    executor:
      name: win/vs2022
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - run:
          name: "Run Build step"
          command: dotnet.exe build
      - run:
          name: "Test the executable"
          command: dotnet.exe test
